#spring.application.name=Rohit'sJournalApp
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
# we are not set username and password yet so we are commenting it now

spring.data.mongodb.uri=mongodb+srv://potdarrohit60_db_user:2yDvhhFDdJ5linkU@cluster0.8jgsxba.mongodb.net/journalEntry_6?retryWrites=true&w=majority&appName=Cluster0
server.port=8087
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG

#if we are not giving the password here then springboot give it us in the console
# and we can give the username in the postman also

# AES Encryption Configuration
external.encryption.key=PdRgUkXp2s5v8y/B

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationInMyJournalApp2024
jwt.expiration=86400000

# Admin Configuration
admin.creation.key=SUPER_SECRET_ADMIN_KEY_2024


